# Generated by Django 6.0.8 on 2026-08-24 08:08

import django.core.validators
import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='camera_floorplans/')),
                ('comments', models.TextField(blank=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='camera_floorplans', to='dcim.location')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera_floorplans', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['site', 'location', 'name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CameraPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('camera_type', models.CharField(default='other', max_length=10)),
                ('x_pct', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('y_pct', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('direction_degrees', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(359)])),
                ('power_source_override', models.CharField(blank=True, default='', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplan_placements', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('floorplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='netbox_camera_floorplan.floorplan')),
            ],
            options={
                'ordering': ['floorplan', 'device'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='floorplan',
            constraint=models.UniqueConstraint(fields=('site', 'location', 'name'), name='unique_floorplan_per_site_location_name'),
        ),
        migrations.AddConstraint(
            model_name='cameraplacement',
            constraint=models.UniqueConstraint(fields=('floorplan', 'device'), name='unique_device_per_floorplan'),
        ),
    ]
