# Generated by Django 6.0.8 on 2026-08-24 10:28

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_camera_floorplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('preset_icon', models.CharField(blank=True, max_length=20)),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='camera_floorplan_icons/')),
                ('color', models.CharField(default='#f2a65a', max_length=7)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='cameraplacement',
            name='camera_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placements', to='netbox_camera_floorplan.cameratype'),
        ),
    ]
