# Generated by Django 6.0.8 on 2026-08-25 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_camera_floorplan', '0002_cameratype_alter_cameraplacement_camera_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cameraplacement',
            name='unique_device_per_floorplan',
        ),
        migrations.AddField(
            model_name='cameratype',
            name='fov_degrees',
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddConstraint(
            model_name='cameraplacement',
            constraint=models.UniqueConstraint(fields=('device',), name='unique_device_placement'),
        ),
    ]
