# Generated by Django 6.0.8 on 2026-08-26 03:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_camera_floorplan', '0003_remove_cameraplacement_unique_device_per_floorplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameratype',
            name='fov_degrees',
            field=models.PositiveSmallIntegerField(default=90, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)]),
        ),
    ]
