# Generated by Django 6.0.8 on 2026-08-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_camera_floorplan', '0004_alter_cameratype_fov_degrees'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameratype',
            name='category',
            field=models.CharField(default='camera', max_length=20),
        ),
    ]
