# Generated by Django 6.0.8 on 2026-08-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_camera_floorplan', '0005_cameratype_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cameraplacement',
            options={'ordering': ['floorplan__site__name', 'floorplan__location__name', 'floorplan__name', 'device__name']},
        ),
        migrations.AlterModelOptions(
            name='floorplan',
            options={'ordering': ['site__name', 'location__name', 'name']},
        ),
    ]
