# Generated by Django 6.0.8 on 2026-08-27 15:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
        ('netbox_camera_floorplan', '0008_alter_floorplan_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorplan',
            options={'ordering': ['site__name', 'location__name', 'name']},
        ),
        migrations.AddField(
            model_name='cameraplacement',
            name='connected_nvr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_cameras', to='netbox_camera_floorplan.cameraplacement'),
        ),
        migrations.AddField(
            model_name='cameraplacement',
            name='nvr_channel',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cameratype',
            name='channel_capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cameraplacement',
            name='x_pct',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cameraplacement',
            name='y_pct',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='cameraplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('connected_nvr__isnull', False)), fields=('connected_nvr', 'nvr_channel'), name='unique_nvr_channel_assignment'),
        ),
    ]
