# Generated by Django 6.0.8 on 2026-08-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_camera_floorplan', '0009_alter_floorplan_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='floorplan',
            options={'ordering': ['site__name', 'location__name', 'name'], 'permissions': [('view_cctv', 'Can view read-only CCTV camera floor plans')]},
        ),
    ]
